[private]
default:
 @just --list -u

dump NAME EXPRESSION: 
  cue eval -e {{EXPRESSION}} --out yaml > _rendered/{{NAME}}.yaml

render:
  cue cmd render

[working-directory: "_rendered/my-repo"]
run:
  # @just render
  act -W manual_deploy.yaml --input env=dev --input workflow=terraform
