name: main
"on":
  push:
    paths:
      - terraform/*.tf
      - terraform/*.hcl
      - terraform/*.tfvars
jobs:
  changes:
    name: changes
    runs-on: ubuntu-latest
    outputs:
      changes: ${{ steps.filter.outputs.changes }}
    steps:
      - uses: actions/checkout@v4
      - id: filter
        uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36
        with:
          filters: |
            terraform:
              - terraform/*.tf
              - terraform/*.hcl
              - terraform/*.tfvars
  terraform-deploy-dev:
    if: needs.filter.changes.outputs.terraform == 'true'
    name: deploy
    needs:
      - filter
    uses: ./reusable-apply-iac.yaml
    with:
      tf-workspace: default
      tf-varfile: ""
      tf-path: terraform
  terraform-deploy-test:
    if: needs.filter.changes.outputs.terraform == 'true'
    name: deploy
    needs:
      - filter
      - dev
    uses: ./reusable-apply-iac.yaml
    with:
      tf-workspace: default
      tf-varfile: ""
      tf-path: terraform
  terraform-deploy-prod:
    if: needs.filter.changes.outputs.terraform == 'true'
    name: deploy
    needs:
      - filter
      - test
    uses: ./reusable-apply-iac.yaml
    with:
      tf-workspace: default
      tf-varfile: ""
      tf-path: terraform
