name: manual-deploy
"on":
  workflow_dispatch:
    inputs:
      workflow:
        description: Workflow to apply
        required: true
        type: choice
        options:
          - terraform
      env:
        description: Workflow to apply
        required: true
        type: choice
        options:
          - dev
          - test
          - prod
        default: dev
jobs:
  terraform-deploy-dev:
    if: ${{ github.event.inputs.workflow == 'terraform' && github.event.inputs.env == 'dev' }}
    name: terraform-deploy-dev
    uses: ./reusable-apply-iac.yaml
    with:
      github-environment: dev
      tf-workspace: default
      tf-varfile: ""
      tf-path: terraform
  terraform-deploy-test:
    if: ${{ github.event.inputs.workflow == 'terraform' && github.event.inputs.env == 'test' }}
    name: terraform-deploy-test
    uses: ./reusable-apply-iac.yaml
    with:
      github-environment: test
      tf-workspace: default
      tf-varfile: ""
      tf-path: terraform
  terraform-deploy-prod:
    if: ${{ github.event.inputs.workflow == 'terraform' && github.event.inputs.env == 'prod' }}
    name: terraform-deploy-prod
    uses: ./reusable-apply-iac.yaml
    with:
      github-environment: prod
      tf-workspace: default
      tf-varfile: ""
      tf-path: terraform
