name: pull_reqest
"on":
  pull_request:
    paths:
      - terraform/*.tf
      - terraform/*.hcl
      - terraform/*.tfvars
jobs:
  changes:
    name: changes
    runs-on: ubuntu-latest
    outputs:
      changes: ${{ steps.filter.outputs.changes }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36
        id: filter
        with:
          filters: |
            terraform:
              - terraform/*.tf
              - terraform/*.hcl
              - terraform/*.tfvars
            frontend:
              - frontend/**
  terraform-preview-dev:
    if: needs.filter.changes.outputs.terraform == 'true'
    name: preview
    needs:
      - filter
    uses: ./reusable-apply-iac.yaml
  terraform-preview-test:
    if: needs.filter.changes.outputs.terraform == 'true'
    name: preview
    needs:
      - filter
      - dev
    uses: ./reusable-apply-iac.yaml
  terraform-preview-prod:
    if: needs.filter.changes.outputs.terraform == 'true'
    name: preview
    needs:
      - filter
      - test
    uses: ./reusable-apply-iac.yaml
