name: test
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "test"
    if: false
  deploy-backend:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - run: echo "deploy"
    # if: needs.changes.outputs.backend == 'true'
